// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diy_Project.Models
{
    public partial class ContactDetail
    {
        public ContactDetail(int iD, string phoneNumber, string email, string telephone, string afterHours)
        {
            ID = iD;
            PhoneNumber = phoneNumber;
            Email = email;
            Telephone = telephone;
            AfterHours = afterHours;
        }

        public int ID { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string AfterHours { get; set; }
    }
}