// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diy_Project.Models
{
    public partial class Service
    {
        public Service(int iD, string providerName, string service1, string description, decimal callOutFee)
        {
            ID = iD;
            ProviderName = providerName;
            Service1 = service1;
            Description = description;
            CallOutFee = callOutFee;
        }

        public int ID { get; set; }
        public string ProviderName { get; set; }
        public string Service1 { get; set; }
        public string Description { get; set; }
        public decimal CallOutFee { get; set; }
    }
}