@startuml

title Project DIY Add new HandyService

box 
    participant HandyPerson
end box
box Services
    participant diyService
    database diyDB
end box


HandyPerson -> diyService: POST v1/handy-service
activate diyService
    note right #Yellow
        ==**Request Body**==
        * name
        * handyPersonId
        * title,
        * description
    end note 

    diyService -> diyDB: BEGIN TRANSACTION
    activate diyDB
        note right #Aqua
            ==**SQL**==
                EXECUTE HandyServices_create
                @Name = ?,
                @HandyPersonId = ?,
                @Title = ?,
                @Description = ?,
            ==**PARAMS**==
                name
                handyPersonId
                title,
                description
        end note
    diyDB -> diyService: END TRANSACTION
    deactivate diyDB

diyService -> diyService: mapToResponse

alt #pink Unhandled exception
    HandyPerson <<-- diyService: 500 Internal Server Error
    note right
        **messages**: ERROR : Unknown Error Occurred
    end note
else #pink Empty param
    HandyPerson <<-- diyService: 400 Bad Request
    note right
        **messages**: ERROR : Param is missing
    end note
else #lightgreen
    HandyPerson <- diyService: 201 Created
end alt

@enduml